apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tv
  namespace: argocd
spec:
  description: "Apps related to media consumption"
  sourceRepos:
  - '*'
  destinations:
  - server: 'https://kubernetes.default.svc'
    namespace: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'