apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: homeassistant
  name: homeassistant
  namespace: home-assistant
spec:
  ports:
    - name: http
      port: 8123
      targetPort: 8123
  selector:
    io.kompose.service: homeassistant
