apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seerr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"  
spec:
  destination:
    namespace: tv
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/jakelooker/k8s-config.git
      targetRevision: main
      ref: values
    - chart: unifi
      repoURL: ghcr.io/fallenbagel/jellyseerr
      targetRevision: 2.7.0
      helm:
        valueFiles:
          - $values/apps/seerr/values.yaml
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m