deploymentStrategy:
  type: Recreate
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 2001
  runAsGroup: 2001
  fsGroup: 2001
#runtimeClassName: "nvidia"
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: "default-redirect-https@kubernetescrd"
  hosts:
    - host: jellyfin.dev.myogg.net
      paths:
        - path: /
          pathType: ImplementationSpecific
livenessProbe:
  initialDelaySeconds: 10
  tcpSocket:
    port: http
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 1
  periodSeconds: 60
readinessProbe:
  initialDelaySeconds: 10
  tcpSocket:
    port: http
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 1
  periodSeconds: 30        
persistence:
  config:
    enabled: true
    existingClaim: "jellyfin-config"
  media:
    enabled: true
    existingClaim: "jellyfin-media"
    storageClass: "local-path"