apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: global-deny-all-ingress
  namespace: metallb-system
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
  namespace: metallb-system
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
