apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: prereq
  sources:
    - repoURL: https://github.com/jakelooker/k8s-config.git
      targetRevision: main
      ref: values
    - chart: gpu-operator
      repoURL:  https://helm.ngc.nvidia.com/nvidia
      targetRevision: v25.10.0
      helm:
        valueFiles:
          - $values/apps/nvidia/values.yaml
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=false
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m