apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    - repoURL: https://charts.longhorn.io
      targetRevision: 1.10.0 
      chart: longhorn
    - repoURL: https://github.com/jakelooker/k8s-config.git
      targetRevision: HEAD
      ref: values
  helm:
    valuesFile:
      - $values/applicationDefs/longhorn/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
