apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io
      targetRevision: 1.10.0
      helm:
        valueFiles:
          - $values/applicationDefs/longhorn/values.yaml
    - repoURL: https://github.com/jakelooker/k8s-config.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true 
