apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-nfs
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  volumeName: ""
  nfs:
    server: 192.168.50.2
    path: "/mnt/swolish/noBackup/media/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: tv
spec:
  resources:
    requests:
      storage: 25Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "local-path"
  volumeName: ""