apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-nfs
spec:
  capacity:
    storage: 20Ti
  accessModes:
    - ReadWriteMany
  storageClassName: "local-path"
  nfs:
    server: 192.168.50.2
    path: "/mnt/swolish/noBackup/media/media"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: tv
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "local-path"
  volumeName: jellyfin-media-nfs