apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: metallb
      repoURL: https://metallb.github.io/metallb
      targetRevision: 0.15.2
      helm:
        valueFiles:
          - $values/apps/metallb/values.yaml
    - repoURL: https://github.com/jakelooker/k8s-config.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true 
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m      
