apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/jakelooker/k8s-config.git
      targetRevision: main
      path: apps/metallb/config
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
    - CreateNamespace=true 
