apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jakelooker/k8s-config.git
    targetRevision: main
    path: apps/ha/config
    
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
